
USE SONG;

-- DROP TABLE IESO_REALTIMECONSTTOTALS;
CREATE TABLE IF NOT EXISTS IESO_RealtimeConstTotals (
    DDATE DATE,
    HOUR INT,
    DINTERVAL INT,
    TOTAL_ENERGY FLOAT,
    TOTAL_10S FLOAT,
    TOTAL_10N FLOAT,
    TOTAL_30R FLOAT,
    TOTAL_DISP_LOAD FLOAT,
    TOTAL_LOAD FLOAT,
    TOTAL_LOSS FLOAT,
    PRIMARY KEY (DDATE, HOUR, DINTERVAL)
    );


-- DROP TABLE NYISO_5_Minute_Price;
CREATE TABLE IF NOT EXISTS NYISO_5_Minute_Price (
    DDATE DATE,
    HOUR INT,
    DINTERVAL INT,
    NAME CHAR(10),
    PTID INT,
    LBMP FLOAT,
    MARGINAL_COST_LOSSES FLOAT,
    MARGINAL_COST_CONGESTION FLOAT,
    PRIMARY KEY (DDATE, HOUR, DINTERVAL, PTID)
    );


