
USE SONG;

-- DROP TABLE IESO_REALTIMECONSTTOTALS;
CREATE TABLE IF NOT EXISTS IESO_RealtimeConstTotals (
    DDATE DATE,
    HOUR INT,
    DINTERVAL INT,
    TOTAL_ENERGY FLOAT,
    TOTAL_10S FLOAT,
    TOTAL_10N FLOAT,
    TOTAL_30R FLOAT,
    TOTAL_DISP_LOAD FLOAT,
    TOTAL_LOAD FLOAT,
    TOTAL_LOSS FLOAT,
    PRIMARY KEY (DDATE, HOUR, DINTERVAL)
    );



