package gosigma.etl;

import java.io.IOException;
import java.util.HashMap;
import java.util.Map;

import org.jsoup.Jsoup;
import org.jsoup.nodes.Attribute;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;
import org.jsoup.parser.Parser;
import org.jsoup.select.Elements;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class FeedLoadParseApp {
	final static Logger logger = LoggerFactory.getLogger(FeedLoadParseApp.class);

	public static void main(String[] args) throws IOException {
		logger.info("Entering...");
		// TODO Auto-generated method stub
		// loadHtml();

		// load_lmppost();
		load_lmppost_static();

		logger.info("Leaving...");
	}

	public static void loadHtml() throws IOException {
		logger.info("Entering...");

		String url = "http://localhost:8080/webapp/dynamic.html";
		Document doc = Jsoup.connect(url).get();
		String title = doc.title();
		System.out.println(title);

		// System.out.println(doc.html());

		logger.info("Leaving...");

	}

	public static void load_lmppost() throws IOException {
		logger.info("Entering...");

		String url = "http://www.pjm.com/pub/account/lmpgen/lmppost.html";
		Document doc = Jsoup.connect(url).get();
		String title = doc.title();
		logger.info(title);

		//		logger.info("---- all children ----");
		//		listChildren(doc.select(":root").get(0), ":root");

		logger.info("---- doc html ----");
		logger.info(doc.html());

		String path = ":root html head title";
		Element e = select(doc, path);

		//		String path = ":root :html";
		//		Elements es = doc.select(":root").select("html").select("body");
		//		logger.info("element " + path + " - " + es.size());

		Elements es = doc.select("b");
		logger.info("b[0] : " + es.get(0).toString());

		// parse path from root
		es = doc.select(">html>head>title");
		logger.info("title[0] : " + es.get(0).ownText());

		logger.info("Leaving...");
	}

	public static void load_lmppost_static() throws IOException {
		logger.info("Entering...");

		//		String url = "http://www.pjm.com/pub/account/lmpgen/lmppost.html";
		//		Document doc = Jsoup.connect(url).get();
		Document doc = Jsoup.parse(htmlText, "", Parser.htmlParser());
		String title = doc.title();
		logger.info(title);

		logger.info("---- all children ----");
		// listELementByPath(doc.select(":root").get(0), ":root");
		listCsvStyle(doc.select(":root").get(0));

		//		logger.info("---- doc html ----");
		//		logger.info(doc.html());

		String path = ":root html head title";
		Element e = select(doc, path);

		//		String path = ":root :html";
		//		Elements es = doc.select(":root").select("html").select("body");
		//		logger.info("element " + path + " - " + es.size());

		Elements es = doc.select("b");
		logger.info("b[0] : " + es.get(0).toString());

		// parse path from root
		es = doc.select(">html>head>title");
		logger.info("title[0] : " + es.get(0).ownText());

		logger.info("Leaving...");
	}

	public static Element select(Document doc, String path) {
		logger.info("select : " + path);
		String[] nodes = path.split(" ");
		logger.info("nodes : " + String.join("|", nodes));
		return null;
	}

	public static void listCsvStyle(Element e) {
		// td tag for continue lines
		if (e.tagName().equalsIgnoreCase("td")) {
			if (!e.text().isEmpty())
				System.out.print(e.text() + ',');
		} else {
			System.out.println(e.ownText());
			for (Element c : e.children()) {
				listCsvStyle(c);
			}
		}
	}

	public static void listChildren(Element e, String prefix) {
		String p = prefix + " " + e.tagName();
		System.out.println(p + " - " + e.ownText());
		for (Element c : e.children()) {
			listChildren(c, p);
		}
	}

	public static void listELementByPath(Element e, String prefix) {
		String p = prefix + ">" + nodeString(e);
		System.out.println(p + " - " + e.ownText());
		Map<String, Integer> orders = new HashMap<>();
		for (Element c : e.children()) {
			Integer val = orders.get(c.tagName());
			if (val == null)
				val = 0;
			else
				val = val + 1;
			orders.put(c.tagName(), val);

			listELementByPath(c, p + "{" + val + "}");
		}
	}

	public static String nodeString(Element e) {
		StringBuilder sb = new StringBuilder();
		// sb.append(e.tagName() + "#" + e.id() + "." + e.className());
		sb.append(e.tagName());
		if (!e.id().equals(""))
			sb.append("#" + e.id());
		//		if (!e.className().equals(""))
		//			sb.append("." + e.className());
		//		for (Attribute a : e.attributes()) {
		//			sb.append("[" + a.getKey() + "='" + a.getValue() + "']");
		//		}
		return sb.toString();
	}

	public static String htmlText = "<html>\r\n" + " <head> \r\n"
			+ "  <title>LMP Oasis posting</title> \r\n"
			+ "  <meta HTTP-EQUIV=\"refresh\" content=\"120\"> \r\n" + " </head> \r\n"
			+ " <body> \r\n" + "  <br> \r\n" + "  <br> \r\n" + "  <h1>\r\n" + "   <center>\r\n"
			+ "    PJM Operational Data\r\n" + "   </center></h1> \r\n" + "  <h2>\r\n"
			+ "   <center>\r\n"
			+ "    This is provided for informational purposes ONLY and should\r\n"
			+ "   </center></h2> \r\n" + "  <h2>\r\n" + "   <center>\r\n"
			+ "    not be relied upon by any party for the actual billing values.\r\n"
			+ "   </center></h2> \r\n" + "  <br> \r\n" + "  <br> \r\n"
			+ "  <!-- Error Message --> \r\n" + "  <br> \r\n" + "  <br> \r\n" + "  <center>\r\n"
			+ "   <h2>Data Last Updated</h2>\r\n" + "  </center> \r\n" + "  <center> \r\n"
			+ "   <table align=\"CENTER\" border=\"5\" cellpadding=\"0\"> \r\n" + "    <tbody>\r\n"
			+ "     <tr> \r\n"
			+ "      <td width=\"350\" align=\"center\"><font size=\"+1\"><b>Sat Dec 16 19:40:00 EST 2017</b></font></td> \r\n"
			+ "     </tr> \r\n" + "    </tbody>\r\n" + "   </table> \r\n" + "  </center> \r\n"
			+ "  <br>\r\n" + "  <br>\r\n" + "  <br> \r\n" + "  <center>\r\n"
			+ "   <h2>Aggregate Locational Marginal Prices (LMP)</h2>\r\n" + "  </center> \r\n"
			+ "  <center> \r\n" + "   <table align=\"CENTER\" border=\"5\" cellpadding=\"0\"> \r\n"
			+ "    <tbody>\r\n" + "     <tr> \r\n"
			+ "      <td width=\"130\" align=\"center\"><b>Name</b></td> \r\n"
			+ "      <td width=\"120\" align=\"center\"><b>Type</b></td> \r\n"
			+ "      <td width=\"120\" align=\"center\"><b>5 Minute Weighted Avg. LMP</b></td> \r\n"
			+ "      <td width=\"180\" align=\"center\"><b>Hourly Integrated LMP for Hour Ending 19</b></td> \r\n"
			+ "     </tr> \r\n" + "     <tr> \r\n" + "      <td>AECO</td> \r\n"
			+ "      <td>ZONE</td> \r\n" + "      <td align=\"right\">33.9</td> \r\n"
			+ "      <td align=\"right\">35.6</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>AEP</td> \r\n" + "      <td>ZONE</td> \r\n"
			+ "      <td align=\"right\">31.4</td> \r\n"
			+ "      <td align=\"right\">33.2</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>APS</td> \r\n" + "      <td>ZONE</td> \r\n"
			+ "      <td align=\"right\">32.8</td> \r\n"
			+ "      <td align=\"right\">34.6</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>ATSI</td> \r\n" + "      <td>ZONE</td> \r\n"
			+ "      <td align=\"right\">33.1</td> \r\n"
			+ "      <td align=\"right\">35.0</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>BGE</td> \r\n" + "      <td>ZONE</td> \r\n"
			+ "      <td align=\"right\">34.2</td> \r\n"
			+ "      <td align=\"right\">36.1</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>COMED</td> \r\n" + "      <td>ZONE</td> \r\n"
			+ "      <td align=\"right\">28.6</td> \r\n"
			+ "      <td align=\"right\">31.7</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>DAY</td> \r\n" + "      <td>ZONE</td> \r\n"
			+ "      <td align=\"right\">33.8</td> \r\n"
			+ "      <td align=\"right\">34.2</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>DEOK</td> \r\n" + "      <td>ZONE</td> \r\n"
			+ "      <td align=\"right\">36.3</td> \r\n"
			+ "      <td align=\"right\">33.2</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>DOM</td> \r\n" + "      <td>ZONE</td> \r\n"
			+ "      <td align=\"right\">33.4</td> \r\n"
			+ "      <td align=\"right\">35.2</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>DPL</td> \r\n" + "      <td>ZONE</td> \r\n"
			+ "      <td align=\"right\">34.5</td> \r\n"
			+ "      <td align=\"right\">36.5</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>DUQ</td> \r\n" + "      <td>ZONE</td> \r\n"
			+ "      <td align=\"right\">32.5</td> \r\n"
			+ "      <td align=\"right\">34.3</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>EKPC</td> \r\n" + "      <td>ZONE</td> \r\n"
			+ "      <td align=\"right\">31.6</td> \r\n"
			+ "      <td align=\"right\">32.4</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>JCPL</td> \r\n" + "      <td>ZONE</td> \r\n"
			+ "      <td align=\"right\">33.9</td> \r\n"
			+ "      <td align=\"right\">35.9</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>METED</td> \r\n" + "      <td>ZONE</td> \r\n"
			+ "      <td align=\"right\">33.5</td> \r\n"
			+ "      <td align=\"right\">35.5</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>PECO</td> \r\n" + "      <td>ZONE</td> \r\n"
			+ "      <td align=\"right\">33.5</td> \r\n"
			+ "      <td align=\"right\">35.4</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>PENELEC</td> \r\n" + "      <td>ZONE</td> \r\n"
			+ "      <td align=\"right\">33.1</td> \r\n"
			+ "      <td align=\"right\">35.1</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>PEPCO</td> \r\n" + "      <td>ZONE</td> \r\n"
			+ "      <td align=\"right\">33.8</td> \r\n"
			+ "      <td align=\"right\">35.6</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>PPL</td> \r\n" + "      <td>ZONE</td> \r\n"
			+ "      <td align=\"right\">33.3</td> \r\n"
			+ "      <td align=\"right\">35.2</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>PSEG</td> \r\n" + "      <td>ZONE</td> \r\n"
			+ "      <td align=\"right\">34.0</td> \r\n"
			+ "      <td align=\"right\">35.9</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>RECO</td> \r\n" + "      <td>ZONE</td> \r\n"
			+ "      <td align=\"right\">34.0</td> \r\n"
			+ "      <td align=\"right\">36.0</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>CPLEEXP</td> \r\n" + "      <td>INTERFACE</td> \r\n"
			+ "      <td align=\"right\">31.9</td> \r\n"
			+ "      <td align=\"right\">33.5</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>CPLEIMP</td> \r\n" + "      <td>INTERFACE</td> \r\n"
			+ "      <td align=\"right\">31.4</td> \r\n"
			+ "      <td align=\"right\">33.1</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>DUKEXP</td> \r\n" + "      <td>INTERFACE</td> \r\n"
			+ "      <td align=\"right\">31.5</td> \r\n"
			+ "      <td align=\"right\">33.1</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>DUKIMP</td> \r\n" + "      <td>INTERFACE</td> \r\n"
			+ "      <td align=\"right\">31.2</td> \r\n"
			+ "      <td align=\"right\">32.9</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>HUDSONTP</td> \r\n" + "      <td>INTERFACE</td> \r\n"
			+ "      <td align=\"right\">35.4</td> \r\n"
			+ "      <td align=\"right\">37.4</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>IMO</td> \r\n" + "      <td>INTERFACE</td> \r\n"
			+ "      <td align=\"right\">31.0</td> \r\n"
			+ "      <td align=\"right\">34.3</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>LINDENVFT</td> \r\n" + "      <td>INTERFACE</td> \r\n"
			+ "      <td align=\"right\">34.0</td> \r\n"
			+ "      <td align=\"right\">36.0</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>MISO</td> \r\n" + "      <td>INTERFACE</td> \r\n"
			+ "      <td align=\"right\">27.6</td> \r\n"
			+ "      <td align=\"right\">31.5</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>NCMPAEXP</td> \r\n" + "      <td>INTERFACE</td> \r\n"
			+ "      <td align=\"right\">31.4</td> \r\n"
			+ "      <td align=\"right\">33.0</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>NCMPAIMP</td> \r\n" + "      <td>INTERFACE</td> \r\n"
			+ "      <td align=\"right\">31.4</td> \r\n"
			+ "      <td align=\"right\">33.0</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>NEPTUNE</td> \r\n" + "      <td>INTERFACE</td> \r\n"
			+ "      <td align=\"right\">33.8</td> \r\n"
			+ "      <td align=\"right\">35.7</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>NIPSCO</td> \r\n" + "      <td>INTERFACE</td> \r\n"
			+ "      <td align=\"right\">28.8</td> \r\n"
			+ "      <td align=\"right\">31.8</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>NORTHWEST</td> \r\n" + "      <td>INTERFACE</td> \r\n"
			+ "      <td align=\"right\">27.9</td> \r\n"
			+ "      <td align=\"right\">31.0</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>NYIS</td> \r\n" + "      <td>INTERFACE</td> \r\n"
			+ "      <td align=\"right\">33.7</td> \r\n"
			+ "      <td align=\"right\">35.7</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>OVEC</td> \r\n" + "      <td>INTERFACE</td> \r\n"
			+ "      <td align=\"right\">30.4</td> \r\n"
			+ "      <td align=\"right\">32.0</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>SOUTHEXP</td> \r\n" + "      <td>INTERFACE</td> \r\n"
			+ "      <td align=\"right\">29.8</td> \r\n"
			+ "      <td align=\"right\">32.3</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>SOUTHIMP</td> \r\n" + "      <td>INTERFACE</td> \r\n"
			+ "      <td align=\"right\">29.8</td> \r\n"
			+ "      <td align=\"right\">32.3</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>AEC - AP</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">32.6</td> \r\n"
			+ "      <td align=\"right\">34.4</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>AEC - JC</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">35.1</td> \r\n"
			+ "      <td align=\"right\">37.2</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>AEC - ME</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">33.3</td> \r\n"
			+ "      <td align=\"right\">35.2</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>AEC - PN</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">33.2</td> \r\n"
			+ "      <td align=\"right\">35.2</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>AELC</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">28.4</td> \r\n"
			+ "      <td align=\"right\">31.4</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>AEP W.O. MON POWER</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">31.3</td> \r\n"
			+ "      <td align=\"right\">33.1</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>AEPOHIO W.O. MON POWER</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">32.1</td> \r\n"
			+ "      <td align=\"right\">33.5</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>AK STEEL</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">28.1</td> \r\n"
			+ "      <td align=\"right\">31.2</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>AMP-ATSI</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">32.9</td> \r\n"
			+ "      <td align=\"right\">34.8</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>AMP-ATSI OH</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">32.9</td> \r\n"
			+ "      <td align=\"right\">34.8</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>AMP-ATSI PA</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">32.8</td> \r\n"
			+ "      <td align=\"right\">34.7</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>AMP-METED</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">33.5</td> \r\n"
			+ "      <td align=\"right\">35.3</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>AMP-OHIO</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">31.8</td> \r\n"
			+ "      <td align=\"right\">33.4</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>AURORA CT 1-4</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">28.4</td> \r\n"
			+ "      <td align=\"right\">31.5</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>BATAVIA</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">28.4</td> \r\n"
			+ "      <td align=\"right\">31.5</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>BATH COUNTY GEN</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">31.7</td> \r\n"
			+ "      <td align=\"right\">33.2</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>BAYONNE TECH</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">34.4</td> \r\n"
			+ "      <td align=\"right\">36.3</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>BAYVIEW</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">39.8</td> \r\n"
			+ "      <td align=\"right\">42.0</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>BERLIN DPL</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">35.8</td> \r\n"
			+ "      <td align=\"right\">37.8</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>BLAKELY BORO</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">33.5</td> \r\n"
			+ "      <td align=\"right\">35.3</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>BLUE RIDGE</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">32.1</td> \r\n"
			+ "      <td align=\"right\">33.6</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>BRANDONSH</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">33.9</td> \r\n"
			+ "      <td align=\"right\">35.8</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>BRUNSWICK</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">33.7</td> \r\n"
			+ "      <td align=\"right\">35.7</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>BUCK-CIN</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">35.7</td> \r\n"
			+ "      <td align=\"right\">33.3</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>BUCK-FE</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">33.0</td> \r\n"
			+ "      <td align=\"right\">35.0</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>BUCKEYE - AEP</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">32.1</td> \r\n"
			+ "      <td align=\"right\">33.5</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>BUCKEYE - DPL</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">33.8</td> \r\n"
			+ "      <td align=\"right\">34.7</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>BUCKEYE - WEC</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">31.1</td> \r\n"
			+ "      <td align=\"right\">32.6</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>CAMDEN TECH</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">33.4</td> \r\n"
			+ "      <td align=\"right\">35.3</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>CATAWISSA</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">31.9</td> \r\n"
			+ "      <td align=\"right\">33.8</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>CHAMBERS CCLP</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">33.2</td> \r\n"
			+ "      <td align=\"right\">35.0</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>CITIZENS</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">32.6</td> \r\n"
			+ "      <td align=\"right\">34.5</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>CLINCH RIVER 1-3</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">30.5</td> \r\n"
			+ "      <td align=\"right\">31.9</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>CONOWINGO GEN 1-11</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">33.4</td> \r\n"
			+ "      <td align=\"right\">35.3</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>COOKSTOWN</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">33.6</td> \r\n"
			+ "      <td align=\"right\">35.6</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>CORDOVA</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">27.3</td> \r\n"
			+ "      <td align=\"right\">30.4</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>CPP</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">33.4</td> \r\n"
			+ "      <td align=\"right\">35.3</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>CRISFIELD</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">37.0</td> \r\n"
			+ "      <td align=\"right\">39.1</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>DECAM COAL GEN</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">33.4</td> \r\n"
			+ "      <td align=\"right\">32.3</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>DECAM GAS GEN</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">30.9</td> \r\n"
			+ "      <td align=\"right\">32.5</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>DEK</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">36.3</td> \r\n"
			+ "      <td align=\"right\">33.0</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>DELI</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">27.5</td> \r\n"
			+ "      <td align=\"right\">30.6</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>DEMEC</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">33.8</td> \r\n"
			+ "      <td align=\"right\">35.7</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>DENAWASH</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">30.9</td> \r\n"
			+ "      <td align=\"right\">32.3</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>DOVER</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">33.6</td> \r\n"
			+ "      <td align=\"right\">35.5</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>DPL NORTH</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">33.2</td> \r\n"
			+ "      <td align=\"right\">35.1</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>DPL SOUTH</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">35.6</td> \r\n"
			+ "      <td align=\"right\">37.6</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>DPL_ODEC</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">35.8</td> \r\n"
			+ "      <td align=\"right\">37.9</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>DRESDEN CC</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">30.7</td> \r\n"
			+ "      <td align=\"right\">32.0</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>DUNCANNON</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">32.6</td> \r\n"
			+ "      <td align=\"right\">34.5</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>EAGLE POINT</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">33.3</td> \r\n"
			+ "      <td align=\"right\">35.2</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>EAST BEND 2</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">18.6</td> \r\n"
			+ "      <td align=\"right\">30.4</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>EASTON</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">34.9</td> \r\n"
			+ "      <td align=\"right\">36.9</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>ECRRF</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">34.2</td> \r\n"
			+ "      <td align=\"right\">36.1</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>EKPC-DEOK LOAD</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">38.9</td> \r\n"
			+ "      <td align=\"right\">33.1</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>ELGIN EC3</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">28.5</td> \r\n"
			+ "      <td align=\"right\">31.5</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>ELIZABETHTOWN</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">31.6</td> \r\n"
			+ "      <td align=\"right\">33.3</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>EPHRATA</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">33.6</td> \r\n"
			+ "      <td align=\"right\">35.6</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>FAIRLAWN</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">34.3</td> \r\n"
			+ "      <td align=\"right\">36.3</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>FE GEN</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">32.3</td> \r\n"
			+ "      <td align=\"right\">34.1</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>FE OHIO</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">33.0</td> \r\n"
			+ "      <td align=\"right\">34.9</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>FRONT ROYAL - AP</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">32.8</td> \r\n"
			+ "      <td align=\"right\">34.5</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>GENEVA</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">28.5</td> \r\n"
			+ "      <td align=\"right\">31.5</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>GIRARD</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">33.4</td> \r\n"
			+ "      <td align=\"right\">35.4</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>GOLDSBORO</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">33.3</td> \r\n"
			+ "      <td align=\"right\">35.0</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>GORSUCH</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">31.3</td> \r\n"
			+ "      <td align=\"right\">33.0</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>GRAND POINT</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">34.6</td> \r\n"
			+ "      <td align=\"right\">36.4</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>GRANDPOINT T1</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">34.6</td> \r\n"
			+ "      <td align=\"right\">36.4</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>GREENUP</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">31.6</td> \r\n"
			+ "      <td align=\"right\">32.5</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>HAGERSTOWN - AP</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">33.8</td> \r\n"
			+ "      <td align=\"right\">35.7</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>HANDSOME LAKE</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">32.8</td> \r\n"
			+ "      <td align=\"right\">34.7</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>HATFIELD - PL</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">33.3</td> \r\n"
			+ "      <td align=\"right\">35.3</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>HAZLETON 1-4</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">32.9</td> \r\n"
			+ "      <td align=\"right\">34.8</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>HAZLETON 2-3</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">32.9</td> \r\n"
			+ "      <td align=\"right\">34.8</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>HAZLETON 3-4</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">32.9</td> \r\n"
			+ "      <td align=\"right\">34.8</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>HILLSDALE_PARKRIDGE</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">34.1</td> \r\n"
			+ "      <td align=\"right\">36.1</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>HOMERCIT</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">32.1</td> \r\n"
			+ "      <td align=\"right\">33.8</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>HOMERCIT UNIT1</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">32.1</td> \r\n"
			+ "      <td align=\"right\">33.8</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>HOMERCIT UNIT2</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">32.2</td> \r\n"
			+ "      <td align=\"right\">33.9</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>HOMERCIT UNIT3</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">32.2</td> \r\n"
			+ "      <td align=\"right\">33.9</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>HREA - AP</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">32.5</td> \r\n"
			+ "      <td align=\"right\">34.3</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>HUDSON BC</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">34.3</td> \r\n"
			+ "      <td align=\"right\">36.2</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>HUDSON-LINDEN ABC</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">34.1</td> \r\n"
			+ "      <td align=\"right\">36.1</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>IRONWOOD</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">32.4</td> \r\n"
			+ "      <td align=\"right\">34.3</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>JOLIET 7</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">28.6</td> \r\n"
			+ "      <td align=\"right\">31.6</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>KENDALL 1-2</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">28.3</td> \r\n"
			+ "      <td align=\"right\">31.3</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>KENDALL 3 CC</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">28.3</td> \r\n"
			+ "      <td align=\"right\">31.3</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>KENDALL CT3</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">28.3</td> \r\n"
			+ "      <td align=\"right\">31.3</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>KITTATNY 230</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">33.9</td> \r\n"
			+ "      <td align=\"right\">35.9</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>LANSDALE</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">33.3</td> \r\n"
			+ "      <td align=\"right\">35.3</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>LEHIGHTON</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">33.1</td> \r\n"
			+ "      <td align=\"right\">35.0</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>LEWES DPL</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">35.5</td> \r\n"
			+ "      <td align=\"right\">37.6</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>LIBERTY</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">33.3</td> \r\n"
			+ "      <td align=\"right\">35.2</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>LIDA - AP</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">34.6</td> \r\n"
			+ "      <td align=\"right\">36.5</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>LINDEN A</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">33.9</td> \r\n"
			+ "      <td align=\"right\">35.9</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>LUMBERTON</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">31.6</td> \r\n"
			+ "      <td align=\"right\">33.3</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>MADISON</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">34.1</td> \r\n"
			+ "      <td align=\"right\">32.7</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>MANITOU</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">33.7</td> \r\n"
			+ "      <td align=\"right\">35.6</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>MARION</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">34.3</td> \r\n"
			+ "      <td align=\"right\">36.2</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>MERIDIAN EWHITLEY</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">28.7</td> \r\n"
			+ "      <td align=\"right\">32.2</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>MEYERSDALE WF</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">31.7</td> \r\n"
			+ "      <td align=\"right\">33.4</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>MICHFE</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">31.6</td> \r\n"
			+ "      <td align=\"right\">33.6</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>MIFFLINBURG</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">32.6</td> \r\n"
			+ "      <td align=\"right\">34.5</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>MISO (PRE-ATSI)</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">29.3</td> \r\n"
			+ "      <td align=\"right\">32.1</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>MITCHELL 1</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">31.3</td> \r\n"
			+ "      <td align=\"right\">32.9</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>MON POWER</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">31.3</td> \r\n"
			+ "      <td align=\"right\">32.9</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>MONT ALTO - AP</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">34.2</td> \r\n"
			+ "      <td align=\"right\">36.0</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>MONTVILLE</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">34.1</td> \r\n"
			+ "      <td align=\"right\">36.0</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>MOTIVA</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">32.8</td> \r\n"
			+ "      <td align=\"right\">34.7</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>MUDDY RUN</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">32.6</td> \r\n"
			+ "      <td align=\"right\">34.5</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>NAAMANS</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">33.2</td> \r\n"
			+ "      <td align=\"right\">35.1</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>NAPERVILLE</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">28.5</td> \r\n"
			+ "      <td align=\"right\">31.6</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>NEW CASTLE DIESEL</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">32.8</td> \r\n"
			+ "      <td align=\"right\">34.7</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>NEWARK BAY</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">34.2</td> \r\n"
			+ "      <td align=\"right\">36.1</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>NEWCHURCH CT1-2</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">36.5</td> \r\n"
			+ "      <td align=\"right\">38.6</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>NEWMARTINSVILLE-AP</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">31.6</td> \r\n"
			+ "      <td align=\"right\">33.3</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>NLEBNON</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">33.0</td> \r\n"
			+ "      <td align=\"right\">34.9</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>OCCIDENTAL</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">32.8</td> \r\n"
			+ "      <td align=\"right\">34.7</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>OLYPHANT</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">33.5</td> \r\n"
			+ "      <td align=\"right\">35.3</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>ONTARIO</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">32.0</td> \r\n"
			+ "      <td align=\"right\">34.2</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>ONTELAUNEE</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">32.7</td> \r\n"
			+ "      <td align=\"right\">34.7</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>PAINESVILLE</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">33.1</td> \r\n"
			+ "      <td align=\"right\">35.0</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>PENN POWER</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">32.8</td> \r\n"
			+ "      <td align=\"right\">34.7</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>PENNTECH</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">33.0</td> \r\n"
			+ "      <td align=\"right\">35.2</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>PEPCO DC</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">33.8</td> \r\n"
			+ "      <td align=\"right\">35.7</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>PEPCO MD</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">33.8</td> \r\n"
			+ "      <td align=\"right\">35.6</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>PEPCO SMECO</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">33.4</td> \r\n"
			+ "      <td align=\"right\">35.2</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>PERKASIE</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">33.3</td> \r\n"
			+ "      <td align=\"right\">35.3</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>PERRYMAN 1-2</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">34.0</td> \r\n"
			+ "      <td align=\"right\">35.9</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>PERRYMAN 3-4</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">34.0</td> \r\n"
			+ "      <td align=\"right\">35.9</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>PHILIPPI - AP</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">32.0</td> \r\n"
			+ "      <td align=\"right\">33.8</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>POTTSTOWN NUG</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">34.4</td> \r\n"
			+ "      <td align=\"right\">36.5</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>PPL_ALLUGI</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">33.4</td> \r\n"
			+ "      <td align=\"right\">35.4</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>QUAKERTOWN</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">33.3</td> \r\n"
			+ "      <td align=\"right\">35.3</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>REDOAK CC</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">33.7</td> \r\n"
			+ "      <td align=\"right\">35.6</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>RICHMOND</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">28.2</td> \r\n"
			+ "      <td align=\"right\">32.2</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>RIVER</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">28.9</td> \r\n"
			+ "      <td align=\"right\">31.9</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>ROCHELLE</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">28.6</td> \r\n"
			+ "      <td align=\"right\">31.8</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>ROCK FALLS</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">27.4</td> \r\n"
			+ "      <td align=\"right\">30.6</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>ROCKFORD</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">27.9</td> \r\n"
			+ "      <td align=\"right\">31.0</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>RTEP B0287 SOURCE</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">32.6</td> \r\n"
			+ "      <td align=\"right\">34.5</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>RTEP B0328 SOURCE</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">31.9</td> \r\n"
			+ "      <td align=\"right\">33.6</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>RTEP B0329 SOURCE</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">33.1</td> \r\n"
			+ "      <td align=\"right\">34.7</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>SCHUYLKILL HAVEN</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">32.2</td> \r\n"
			+ "      <td align=\"right\">34.0</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>SENECA</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">32.5</td> \r\n"
			+ "      <td align=\"right\">35.0</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>SOUTH BEND 1-4</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">31.9</td> \r\n"
			+ "      <td align=\"right\">33.7</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>SOUTHEAST</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">31.8</td> \r\n"
			+ "      <td align=\"right\">33.4</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>SOUTHEAST (PRE-DOM)</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">32.1</td> \r\n"
			+ "      <td align=\"right\">33.7</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>SOUTHRIV 230</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">33.7</td> \r\n"
			+ "      <td align=\"right\">35.7</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>SOUTHWEST</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">30.8</td> \r\n"
			+ "      <td align=\"right\">31.9</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>ST CLAIR</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">32.2</td> \r\n"
			+ "      <td align=\"right\">34.0</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>ST. CHARLES</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">28.5</td> \r\n"
			+ "      <td align=\"right\">31.5</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>SULLIVAN</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">32.2</td> \r\n"
			+ "      <td align=\"right\">34.0</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>SUNBURY BUS1E</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">32.6</td> \r\n"
			+ "      <td align=\"right\">34.5</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>SUNBURY BUS1W</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">32.6</td> \r\n"
			+ "      <td align=\"right\">34.5</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>SUNBURY BUS2E</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">32.6</td> \r\n"
			+ "      <td align=\"right\">34.5</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>SUNBURY BUS2W</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">32.6</td> \r\n"
			+ "      <td align=\"right\">34.5</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>SUNBURY LBRG</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">32.6</td> \r\n"
			+ "      <td align=\"right\">34.5</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>SUNOIL</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">33.4</td> \r\n"
			+ "      <td align=\"right\">35.4</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>TANSBORO AE</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">33.3</td> \r\n"
			+ "      <td align=\"right\">35.2</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>TARENTUM - AP</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">31.8</td> \r\n"
			+ "      <td align=\"right\">33.6</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>TEMPLEU</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">33.8</td> \r\n"
			+ "      <td align=\"right\">35.8</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>THURMONT - AP</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">34.0</td> \r\n"
			+ "      <td align=\"right\">35.8</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>TOSCO LOAD BUS</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">33.9</td> \r\n"
			+ "      <td align=\"right\">35.9</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>TRAYNOR</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">34.0</td> \r\n"
			+ "      <td align=\"right\">36.0</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>TRI-COUNTY</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">34.3</td> \r\n"
			+ "      <td align=\"right\">36.3</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>UGI</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">33.4</td> \r\n"
			+ "      <td align=\"right\">35.4</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>VINELAND</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">33.9</td> \r\n"
			+ "      <td align=\"right\">35.1</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>VP KERR DAM 1-7</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">32.9</td> \r\n"
			+ "      <td align=\"right\">34.5</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>WALDWICK JK</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">33.9</td> \r\n"
			+ "      <td align=\"right\">35.9</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>WARREN COUNTY CC</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">32.6</td> \r\n"
			+ "      <td align=\"right\">34.3</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>WATERFORD CC</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">30.8</td> \r\n"
			+ "      <td align=\"right\">32.2</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>WATSONTOWN</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">32.2</td> \r\n"
			+ "      <td align=\"right\">34.0</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>WEATHERLY</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">32.9</td> \r\n"
			+ "      <td align=\"right\">34.8</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>WELLSBORO</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">33.4</td> \r\n"
			+ "      <td align=\"right\">35.3</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>WESTVACO</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">32.4</td> \r\n"
			+ "      <td align=\"right\">34.2</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>WILLIAMSPORT - AP</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">33.7</td> \r\n"
			+ "      <td align=\"right\">35.5</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>WILLIAMSTOWN</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">32.3</td> \r\n"
			+ "      <td align=\"right\">32.1</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>WINNETKA</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">28.7</td> \r\n"
			+ "      <td align=\"right\">31.8</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>ZION 1</td> \r\n" + "      <td>AGGREGATE</td> \r\n"
			+ "      <td align=\"right\">28.3</td> \r\n"
			+ "      <td align=\"right\">31.5</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>AEP GEN HUB</td> \r\n" + "      <td>HUB</td> \r\n"
			+ "      <td align=\"right\">29.6</td> \r\n"
			+ "      <td align=\"right\">32.1</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>AEP-DAYTON HUB</td> \r\n" + "      <td>HUB</td> \r\n"
			+ "      <td align=\"right\">31.1</td> \r\n"
			+ "      <td align=\"right\">33.0</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>ATSI GEN HUB</td> \r\n" + "      <td>HUB</td> \r\n"
			+ "      <td align=\"right\">32.6</td> \r\n"
			+ "      <td align=\"right\">34.5</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>CHICAGO GEN HUB</td> \r\n" + "      <td>HUB</td> \r\n"
			+ "      <td align=\"right\">28.3</td> \r\n"
			+ "      <td align=\"right\">31.3</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>CHICAGO HUB</td> \r\n" + "      <td>HUB</td> \r\n"
			+ "      <td align=\"right\">28.7</td> \r\n"
			+ "      <td align=\"right\">31.8</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>DOMINION HUB</td> \r\n" + "      <td>HUB</td> \r\n"
			+ "      <td align=\"right\">33.3</td> \r\n"
			+ "      <td align=\"right\">34.9</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>EASTERN HUB</td> \r\n" + "      <td>HUB</td> \r\n"
			+ "      <td align=\"right\">34.6</td> \r\n"
			+ "      <td align=\"right\">36.6</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>N ILLINOIS HUB</td> \r\n" + "      <td>HUB</td> \r\n"
			+ "      <td align=\"right\">28.6</td> \r\n"
			+ "      <td align=\"right\">31.6</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>NEW JERSEY HUB</td> \r\n" + "      <td>HUB</td> \r\n"
			+ "      <td align=\"right\">33.9</td> \r\n"
			+ "      <td align=\"right\">35.8</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>OHIO HUB</td> \r\n" + "      <td>HUB</td> \r\n"
			+ "      <td align=\"right\">30.9</td> \r\n"
			+ "      <td align=\"right\">33.0</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>WEST INT HUB</td> \r\n" + "      <td>HUB</td> \r\n"
			+ "      <td align=\"right\">32.3</td> \r\n"
			+ "      <td align=\"right\">34.1</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>WESTERN HUB</td> \r\n" + "      <td>HUB</td> \r\n"
			+ "      <td align=\"right\">33.1</td> \r\n"
			+ "      <td align=\"right\">35.0</td> \r\n" + "     </tr> \r\n" + "    </tbody>\r\n"
			+ "   </table> \r\n" + "  </center> \r\n" + "  <br>\r\n" + "  <br>\r\n" + "  <br> \r\n"
			+ "  <br>\r\n" + "  <br>\r\n" + "  <br> \r\n" + "  <br>\r\n" + "  <br>\r\n"
			+ "  <br> \r\n" + "  <center>\r\n"
			+ "   <h2>500 KV Bus Locational Marginal Prices (LMP)</h2>\r\n" + "  </center> \r\n"
			+ "  <center> \r\n" + "   <table align=\"CENTER\" border=\"5\" cellpadding=\"0\"> \r\n"
			+ "    <tbody>\r\n" + "     <tr> \r\n"
			+ "      <td width=\"150\" align=\"center\"><b>Bus Name</b></td> \r\n"
			+ "      <td width=\"120\" align=\"center\"><b>5 Minute LMP</b></td> \r\n"
			+ "      <td width=\"180\" align=\"center\"><b>Hourly Integrated LMP for Hour Ending 19</b></td> \r\n"
			+ "     </tr> \r\n" + "     <tr> \r\n" + "      <td>112 WILTON</td> \r\n"
			+ "      <td align=\"right\">28.4</td> \r\n"
			+ "      <td align=\"right\">31.4</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>167 PLANO</td> \r\n" + "      <td align=\"right\">28.3</td> \r\n"
			+ "      <td align=\"right\">31.3</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>23 COLLINS</td> \r\n" + "      <td align=\"right\">28.4</td> \r\n"
			+ "      <td align=\"right\">31.3</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>502JCT</td> \r\n" + "      <td align=\"right\">31.7</td> \r\n"
			+ "      <td align=\"right\">33.4</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>ALBURTIS</td> \r\n" + "      <td align=\"right\">33.1</td> \r\n"
			+ "      <td align=\"right\">35.0</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>AMOS</td> \r\n" + "      <td align=\"right\">30.6</td> \r\n"
			+ "      <td align=\"right\">32.1</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>AXTON</td> \r\n" + "      <td align=\"right\">31.2</td> \r\n"
			+ "      <td align=\"right\">32.7</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>BAKER</td> \r\n" + "      <td align=\"right\">30.7</td> \r\n"
			+ "      <td align=\"right\">32.2</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>BATH COUNTY</td> \r\n" + "      <td align=\"right\">31.7</td> \r\n"
			+ "      <td align=\"right\">33.2</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>BEDINGTON</td> \r\n" + "      <td align=\"right\">33.0</td> \r\n"
			+ "      <td align=\"right\">34.8</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>BELMONT</td> \r\n" + "      <td align=\"right\">31.1</td> \r\n"
			+ "      <td align=\"right\">32.7</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>BLACKOAK</td> \r\n" + "      <td align=\"right\">32.4</td> \r\n"
			+ "      <td align=\"right\">34.2</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>BRAMBLET</td> \r\n" + "      <td align=\"right\">33.2</td> \r\n"
			+ "      <td align=\"right\">35.0</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>BRANCHBURG</td> \r\n" + "      <td align=\"right\">33.5</td> \r\n"
			+ "      <td align=\"right\">35.4</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>BRIGHTON</td> \r\n" + "      <td align=\"right\">33.4</td> \r\n"
			+ "      <td align=\"right\">35.2</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>BRISTERS</td> \r\n" + "      <td align=\"right\">33.1</td> \r\n"
			+ "      <td align=\"right\">34.9</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>BRNGSVIL</td> \r\n" + "      <td align=\"right\">33.0</td> \r\n"
			+ "      <td align=\"right\">34.9</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>BROADFORD</td> \r\n" + "      <td align=\"right\">31.0</td> \r\n"
			+ "      <td align=\"right\">32.5</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>BRUNSSWY</td> \r\n" + "      <td align=\"right\">32.4</td> \r\n"
			+ "      <td align=\"right\">34.0</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>BURCHESHILL</td> \r\n" + "      <td align=\"right\">33.4</td> \r\n"
			+ "      <td align=\"right\">35.2</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>CABOT</td> \r\n" + "      <td align=\"right\">32.0</td> \r\n"
			+ "      <td align=\"right\">33.7</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>CALVERTC</td> \r\n" + "      <td align=\"right\">33.3</td> \r\n"
			+ "      <td align=\"right\">35.1</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>CARSON</td> \r\n" + "      <td align=\"right\">32.9</td> \r\n"
			+ "      <td align=\"right\">34.5</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>CENTERPT</td> \r\n" + "      <td align=\"right\">33.2</td> \r\n"
			+ "      <td align=\"right\">35.1</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>CHALKPT</td> \r\n" + "      <td align=\"right\">33.4</td> \r\n"
			+ "      <td align=\"right\">35.2</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>CHANCELLOR</td> \r\n" + "      <td align=\"right\">33.1</td> \r\n"
			+ "      <td align=\"right\">34.9</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>CHELTENH</td> \r\n" + "      <td align=\"right\">33.4</td> \r\n"
			+ "      <td align=\"right\">35.2</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>CHICKAHOMINY</td> \r\n" + "      <td align=\"right\">33.3</td> \r\n"
			+ "      <td align=\"right\">35.1</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>CLIFTON</td> \r\n" + "      <td align=\"right\">33.2</td> \r\n"
			+ "      <td align=\"right\">35.0</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>CLOVER</td> \r\n" + "      <td align=\"right\">32.4</td> \r\n"
			+ "      <td align=\"right\">33.9</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>CLOVERDALE</td> \r\n" + "      <td align=\"right\">31.5</td> \r\n"
			+ "      <td align=\"right\">33.0</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>CONASTONE</td> \r\n" + "      <td align=\"right\">32.9</td> \r\n"
			+ "      <td align=\"right\">34.7</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>CONEMAUGH</td> \r\n" + "      <td align=\"right\">32.0</td> \r\n"
			+ "      <td align=\"right\">33.7</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>COOK</td> \r\n" + "      <td align=\"right\">28.8</td> \r\n"
			+ "      <td align=\"right\">31.7</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>CRANBERRY</td> \r\n" + "      <td align=\"right\">32.0</td> \r\n"
			+ "      <td align=\"right\">33.7</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>CULLODEN</td> \r\n" + "      <td align=\"right\">30.7</td> \r\n"
			+ "      <td align=\"right\">32.2</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>CUNNINGHAM</td> \r\n" + "      <td align=\"right\">31.5</td> \r\n"
			+ "      <td align=\"right\">33.0</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>DEANS</td> \r\n" + "      <td align=\"right\">33.5</td> \r\n"
			+ "      <td align=\"right\">35.5</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>DLTAPLNT</td> \r\n" + "      <td align=\"right\">32.7</td> \r\n"
			+ "      <td align=\"right\">34.6</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>DOOMS</td> \r\n" + "      <td align=\"right\">31.7</td> \r\n"
			+ "      <td align=\"right\">33.2</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>DOUBS</td> \r\n" + "      <td align=\"right\">33.2</td> \r\n"
			+ "      <td align=\"right\">35.0</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>DUMONT</td> \r\n" + "      <td align=\"right\">28.8</td> \r\n"
			+ "      <td align=\"right\">31.8</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>ELMONT</td> \r\n" + "      <td align=\"right\">33.3</td> \r\n"
			+ "      <td align=\"right\">35.0</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>ELROY</td> \r\n" + "      <td align=\"right\">33.2</td> \r\n"
			+ "      <td align=\"right\">35.2</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>ELROYPL</td> \r\n" + "      <td align=\"right\">33.2</td> \r\n"
			+ "      <td align=\"right\">35.2</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>EWINDSOR</td> \r\n" + "      <td align=\"right\">33.5</td> \r\n"
			+ "      <td align=\"right\">35.5</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>FENTRESS</td> \r\n" + "      <td align=\"right\">33.2</td> \r\n"
			+ "      <td align=\"right\">34.8</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>FLATLICK</td> \r\n" + "      <td align=\"right\">30.7</td> \r\n"
			+ "      <td align=\"right\">32.2</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>FLUVANNA</td> \r\n" + "      <td align=\"right\">31.4</td> \r\n"
			+ "      <td align=\"right\">33.0</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>FORTMARTIN</td> \r\n" + "      <td align=\"right\">31.7</td> \r\n"
			+ "      <td align=\"right\">33.4</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>FREEDOM2</td> \r\n" + "      <td align=\"right\">32.7</td> \r\n"
			+ "      <td align=\"right\">34.6</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>FRONT ROYAL</td> \r\n" + "      <td align=\"right\">32.6</td> \r\n"
			+ "      <td align=\"right\">34.4</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>GAVIN</td> \r\n" + "      <td align=\"right\">30.6</td> \r\n"
			+ "      <td align=\"right\">32.2</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>GOOSECRE</td> \r\n" + "      <td align=\"right\">33.2</td> \r\n"
			+ "      <td align=\"right\">35.0</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>GREENLAND GAP</td> \r\n" + "      <td align=\"right\">32.2</td> \r\n"
			+ "      <td align=\"right\">33.9</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>GRNSVIL</td> \r\n" + "      <td align=\"right\">32.4</td> \r\n"
			+ "      <td align=\"right\">34.0</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>HANGING ROCK</td> \r\n" + "      <td align=\"right\">30.5</td> \r\n"
			+ "      <td align=\"right\">32.1</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>HARRISON</td> \r\n" + "      <td align=\"right\">31.6</td> \r\n"
			+ "      <td align=\"right\">33.3</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>HATFIELD</td> \r\n" + "      <td align=\"right\">31.8</td> \r\n"
			+ "      <td align=\"right\">33.6</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>HOPATCON</td> \r\n" + "      <td align=\"right\">33.8</td> \r\n"
			+ "      <td align=\"right\">35.7</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>HOPECREEK</td> \r\n" + "      <td align=\"right\">32.8</td> \r\n"
			+ "      <td align=\"right\">34.7</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>HOSENSACK</td> \r\n" + "      <td align=\"right\">33.1</td> \r\n"
			+ "      <td align=\"right\">35.0</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>HUNTERSTOWN</td> \r\n" + "      <td align=\"right\">32.6</td> \r\n"
			+ "      <td align=\"right\">34.4</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>JACKSONS FERRY</td> \r\n" + "      <td align=\"right\">31.2</td> \r\n"
			+ "      <td align=\"right\">32.7</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>JEFFERSON</td> \r\n" + "      <td align=\"right\">28.7</td> \r\n"
			+ "      <td align=\"right\">31.6</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>JOSHUA FALLS</td> \r\n" + "      <td align=\"right\">31.5</td> \r\n"
			+ "      <td align=\"right\">33.1</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>JUNIATA</td> \r\n" + "      <td align=\"right\">32.6</td> \r\n"
			+ "      <td align=\"right\">34.4</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>KAMMER</td> \r\n" + "      <td align=\"right\">31.4</td> \r\n"
			+ "      <td align=\"right\">33.0</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>KEENEY</td> \r\n" + "      <td align=\"right\">32.9</td> \r\n"
			+ "      <td align=\"right\">34.7</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>KEYSTONE</td> \r\n" + "      <td align=\"right\">31.9</td> \r\n"
			+ "      <td align=\"right\">33.7</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>LACKAWAN</td> \r\n" + "      <td align=\"right\">33.2</td> \r\n"
			+ "      <td align=\"right\">35.1</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>LADYSMITH</td> \r\n" + "      <td align=\"right\">33.1</td> \r\n"
			+ "      <td align=\"right\">34.9</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>LAUSCHTO</td> \r\n" + "      <td align=\"right\">32.9</td> \r\n"
			+ "      <td align=\"right\">34.8</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>LEXINGTON</td> \r\n" + "      <td align=\"right\">31.6</td> \r\n"
			+ "      <td align=\"right\">33.1</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>LIMERICK</td> \r\n" + "      <td align=\"right\">33.1</td> \r\n"
			+ "      <td align=\"right\">35.0</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>LOUDOUN</td> \r\n" + "      <td align=\"right\">33.2</td> \r\n"
			+ "      <td align=\"right\">35.0</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>MALISZEWSKI</td> \r\n" + "      <td align=\"right\">31.0</td> \r\n"
			+ "      <td align=\"right\">32.7</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>MARQUIS</td> \r\n" + "      <td align=\"right\">30.8</td> \r\n"
			+ "      <td align=\"right\">32.1</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>MARYSVILLE</td> \r\n" + "      <td align=\"right\">30.8</td> \r\n"
			+ "      <td align=\"right\">32.6</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>MEADOWBROOK</td> \r\n" + "      <td align=\"right\">32.6</td> \r\n"
			+ "      <td align=\"right\">34.3</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>MIDLOTHIAN</td> \r\n" + "      <td align=\"right\">33.0</td> \r\n"
			+ "      <td align=\"right\">34.6</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>MORRISVILLE</td> \r\n" + "      <td align=\"right\">33.1</td> \r\n"
			+ "      <td align=\"right\">34.8</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>MOSBY</td> \r\n" + "      <td align=\"right\">33.2</td> \r\n"
			+ "      <td align=\"right\">35.0</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>MOUNTAINEER</td> \r\n" + "      <td align=\"right\">30.7</td> \r\n"
			+ "      <td align=\"right\">32.2</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>MT STORM</td> \r\n" + "      <td align=\"right\">32.2</td> \r\n"
			+ "      <td align=\"right\">33.8</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>NAGELAEP</td> \r\n" + "      <td align=\"right\">30.7</td> \r\n"
			+ "      <td align=\"right\">32.3</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>NEWFREEDOM</td> \r\n" + "      <td align=\"right\">33.0</td> \r\n"
			+ "      <td align=\"right\">34.9</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>NORTH ANNA</td> \r\n" + "      <td align=\"right\">33.0</td> \r\n"
			+ "      <td align=\"right\">34.7</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>NORTH LONGVIEW</td> \r\n" + "      <td align=\"right\">31.7</td> \r\n"
			+ "      <td align=\"right\">33.4</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>NORTH PROCTORVILLE</td> \r\n" + "      <td align=\"right\">30.6</td> \r\n"
			+ "      <td align=\"right\">32.1</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>ORCHARD</td> \r\n" + "      <td align=\"right\">32.9</td> \r\n"
			+ "      <td align=\"right\">34.8</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>OX</td> \r\n" + "      <td align=\"right\">33.2</td> \r\n"
			+ "      <td align=\"right\">35.0</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>PEACHBOTTOM</td> \r\n" + "      <td align=\"right\">32.7</td> \r\n"
			+ "      <td align=\"right\">34.6</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>PLEASANT VIEW</td> \r\n" + "      <td align=\"right\">33.2</td> \r\n"
			+ "      <td align=\"right\">35.0</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>PLEASANTS</td> \r\n" + "      <td align=\"right\">31.1</td> \r\n"
			+ "      <td align=\"right\">32.7</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>POSSUM POINT</td> \r\n" + "      <td align=\"right\">33.3</td> \r\n"
			+ "      <td align=\"right\">35.0</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>PRUNTYTOWN</td> \r\n" + "      <td align=\"right\">31.8</td> \r\n"
			+ "      <td align=\"right\">33.4</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>RAWLINGS</td> \r\n" + "      <td align=\"right\">32.6</td> \r\n"
			+ "      <td align=\"right\">34.2</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>REDLION</td> \r\n" + "      <td align=\"right\">32.9</td> \r\n"
			+ "      <td align=\"right\">34.7</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>REYNOLD2</td> \r\n" + "      <td align=\"right\">28.4</td> \r\n"
			+ "      <td align=\"right\">31.7</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>RHODESLN</td> \r\n" + "      <td align=\"right\">32.0</td> \r\n"
			+ "      <td align=\"right\">33.7</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>ROCKPORT</td> \r\n" + "      <td align=\"right\">28.1</td> \r\n"
			+ "      <td align=\"right\">31.2</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>ROCKSPRINGS</td> \r\n" + "      <td align=\"right\">32.8</td> \r\n"
			+ "      <td align=\"right\">34.6</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>ROGERSRD</td> \r\n" + "      <td align=\"right\">32.4</td> \r\n"
			+ "      <td align=\"right\">34.0</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>RONCO</td> \r\n" + "      <td align=\"right\">31.8</td> \r\n"
			+ "      <td align=\"right\">33.5</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>ROSELAND</td> \r\n" + "      <td align=\"right\">33.9</td> \r\n"
			+ "      <td align=\"right\">35.9</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>SALEM</td> \r\n" + "      <td align=\"right\">32.8</td> \r\n"
			+ "      <td align=\"right\">34.6</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>SEPTA</td> \r\n" + "      <td align=\"right\">33.0</td> \r\n"
			+ "      <td align=\"right\">34.6</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>SHICKSHI</td> \r\n" + "      <td align=\"right\">32.7</td> \r\n"
			+ "      <td align=\"right\">34.6</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>SKFFSCRK</td> \r\n" + "      <td align=\"right\">34.2</td> \r\n"
			+ "      <td align=\"right\">36.0</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>SMITHBURG</td> \r\n" + "      <td align=\"right\">33.6</td> \r\n"
			+ "      <td align=\"right\">35.5</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>SORENSON</td> \r\n" + "      <td align=\"right\">28.6</td> \r\n"
			+ "      <td align=\"right\">32.1</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>SOUTH CANTON</td> \r\n" + "      <td align=\"right\">31.8</td> \r\n"
			+ "      <td align=\"right\">33.5</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>SOUTHBEND</td> \r\n" + "      <td align=\"right\">31.9</td> \r\n"
			+ "      <td align=\"right\">33.7</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>SPOTSLV</td> \r\n" + "      <td align=\"right\">33.0</td> \r\n"
			+ "      <td align=\"right\">34.8</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>STEELCITY</td> \r\n" + "      <td align=\"right\">33.0</td> \r\n"
			+ "      <td align=\"right\">35.0</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>SUFFOLK</td> \r\n" + "      <td align=\"right\">33.1</td> \r\n"
			+ "      <td align=\"right\">34.7</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>SULLIVAN-AEP</td> \r\n" + "      <td align=\"right\">27.9</td> \r\n"
			+ "      <td align=\"right\">31.2</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>SUNBURY</td> \r\n" + "      <td align=\"right\">32.6</td> \r\n"
			+ "      <td align=\"right\">34.4</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>SURRY</td> \r\n" + "      <td align=\"right\">33.0</td> \r\n"
			+ "      <td align=\"right\">34.6</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>SUSQUEHANNA</td> \r\n" + "      <td align=\"right\">32.6</td> \r\n"
			+ "      <td align=\"right\">34.5</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>TMI</td> \r\n" + "      <td align=\"right\">32.7</td> \r\n"
			+ "      <td align=\"right\">34.6</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>VALLEY</td> \r\n" + "      <td align=\"right\">31.8</td> \r\n"
			+ "      <td align=\"right\">33.3</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>VASSELL</td> \r\n" + "      <td align=\"right\">31.1</td> \r\n"
			+ "      <td align=\"right\">32.8</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>WAUGHCHAPEL</td> \r\n" + "      <td align=\"right\">33.5</td> \r\n"
			+ "      <td align=\"right\">35.3</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>WESCOSVL</td> \r\n" + "      <td align=\"right\">33.0</td> \r\n"
			+ "      <td align=\"right\">34.9</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>WHITPAIN</td> \r\n" + "      <td align=\"right\">33.2</td> \r\n"
			+ "      <td align=\"right\">35.1</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>WMORELND</td> \r\n" + "      <td align=\"right\">32.0</td> \r\n"
			+ "      <td align=\"right\">33.7</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>WYLIERIDGE</td> \r\n" + "      <td align=\"right\">31.9</td> \r\n"
			+ "      <td align=\"right\">33.7</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>WYOMING</td> \r\n" + "      <td align=\"right\">30.9</td> \r\n"
			+ "      <td align=\"right\">32.4</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>YADKIN</td> \r\n" + "      <td align=\"right\">33.2</td> \r\n"
			+ "      <td align=\"right\">34.8</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>YUKON</td> \r\n" + "      <td align=\"right\">32.0</td> \r\n"
			+ "      <td align=\"right\">33.7</td> \r\n" + "     </tr> \r\n" + "    </tbody>\r\n"
			+ "   </table> \r\n" + "  </center> \r\n" + "  <br>\r\n" + "  <br>\r\n" + "  <br> \r\n"
			+ "  <center>\r\n" + "   <h2>PJM Transfer Interface Information (MW)</h2> \r\n"
			+ "   <table align=\"CENTER\" border=\"5\"> \r\n" + "    <tbody>\r\n" + "     <tr> \r\n"
			+ "      <td width=\"90\" align=\"center\"><b>Interface</b></td> \r\n"
			+ "      <td width=\"100\" align=\"center\"><b>Actual flow</b></td> \r\n"
			+ "      <td width=\"100\" align=\"center\"><b>Warning Level</b></td> \r\n"
			+ "      <td width=\"100\" align=\"center\"><b>Transfer Limit</b></td> \r\n"
			+ "     </tr> \r\n" + "     <tr> \r\n" + "      <td>50045005</td> \r\n"
			+ "      <td align=\"right\">2407</td> \r\n"
			+ "      <td align=\"right\">3447</td> \r\n"
			+ "      <td align=\"right\">4028</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>AEP/DOM</td> \r\n" + "      <td align=\"right\">2188</td> \r\n"
			+ "      <td align=\"right\">3238</td> \r\n"
			+ "      <td align=\"right\">3409</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>APSOUTH</td> \r\n" + "      <td align=\"right\">3544</td> \r\n"
			+ "      <td align=\"right\">4144</td> \r\n"
			+ "      <td align=\"right\">4362</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>BED-BLA</td> \r\n" + "      <td align=\"right\">1522</td> \r\n"
			+ "      <td align=\"right\">1808</td> \r\n"
			+ "      <td align=\"right\">1903</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>CENTRAL</td> \r\n" + "      <td align=\"right\">790</td> \r\n"
			+ "      <td align=\"right\">3799</td> \r\n"
			+ "      <td align=\"right\">3999</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>CLVLND</td> \r\n" + "      <td align=\"right\">1401</td> \r\n"
			+ "      <td align=\"right\">2619</td> \r\n"
			+ "      <td align=\"right\">2757</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>COMED</td> \r\n" + "      <td align=\"right\">-3084</td> \r\n"
			+ "      <td align=\"right\">2430</td> \r\n"
			+ "      <td align=\"right\">2558</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>EAST</td> \r\n" + "      <td align=\"right\">3792</td> \r\n"
			+ "      <td align=\"right\">6047</td> \r\n"
			+ "      <td align=\"right\">6366</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>WEST</td> \r\n" + "      <td align=\"right\">3264</td> \r\n"
			+ "      <td align=\"right\">5341</td> \r\n"
			+ "      <td align=\"right\">5943</td> \r\n" + "     </tr> \r\n" + "    </tbody>\r\n"
			+ "   </table> \r\n" + "  </center> \r\n" + "  <p></p>\r\n" + "  <center>\r\n"
			+ "   Name does not indicate direction.\r\n" + "  </center> \r\n" + "  <br>\r\n"
			+ "  <br>\r\n" + "  <br> \r\n" + "  <center>\r\n"
			+ "   <h2>PJM Instantaneous Dispatch Rates</h2>\r\n" + "  </center> \r\n"
			+ "  <!--  Comes from BSP 128: Should I include this? --> \r\n"
			+ "  <a target=\"_top\" href=\"http://oasis.pjm.com/drate.html\" name=\"Instantaneous Dispatch Rate Page\">\r\n"
			+ "   <center>\r\n" + "    PJM Dispatch Rates\r\n" + "   </center></a> \r\n"
			+ "  <br>\r\n" + "  <br>\r\n" + "  <br> \r\n" + "  <center>\r\n"
			+ "   <h2>PJM Instantaneous Load (MW)</h2>\r\n" + "  </center> \r\n" + "  <center> \r\n"
			+ "   <table align=\"CENTER\" border=\"5\"> \r\n" + "    <tbody>\r\n" + "     <tr> \r\n"
			+ "      <td width=\"150\" align=\"center\"><b>Area</b></td> \r\n"
			+ "      <td width=\"120\" align=\"center\"><b>Instantaneous Load</b></td> \r\n"
			+ "     </tr> \r\n" + "     <tr> \r\n" + "      <td>PJM RTO</td> \r\n"
			+ "      <td align=\"right\">100392</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>PJM MID ATLANTIC REGION</td> \r\n"
			+ "      <td align=\"right\">35829</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>PJM SOUTHERN REGION</td> \r\n"
			+ "      <td align=\"right\">13175</td> \r\n" + "     </tr> \r\n" + "     <tr> \r\n"
			+ "      <td>PJM WESTERN REGION</td> \r\n" + "      <td align=\"right\">51389</td> \r\n"
			+ "     </tr> \r\n" + "    </tbody>\r\n" + "   </table> \r\n" + "  </center> \r\n"
			+ "  <p></p>\r\n" + "  <center>\r\n"
			+ "   Loads are calculated from raw telemetry data and are approximate.\r\n"
			+ "  </center> \r\n" + "  <center>\r\n"
			+ "   The displayed values are NOT official PJM Loads.\r\n" + "  </center> \r\n"
			+ "  <br>\r\n" + "  <br>\r\n" + "  <br> \r\n" + "  <p></p>\r\n" + "  <center>\r\n"
			+ "   <h2>Current PJM Transmission Limits</h2>\r\n" + "  </center> \r\n"
			+ "  <p align=\"center\"> Contingency EBEND 345 KV EBEND 1579 CB EBEND 345 KV EBEND 1583 CB LINE 345 KV EBEND-TERMINAL 4516 TERMINAL 345 KV TERMINAL 1301 CB TERMINAL 345 KV TERMINAL 1307 CB <br>Monitor TANNERSC-MIAMIFOR 4504 B 345 KV -&gt; Redispatch<br>   </p>\r\n"
			+ " </body>\r\n" + "</html>";
}
