'''

@author: xyj
'''

import requests
import json

url = 'http://localhost:8080/test/01'
data = '''
        { 
            DOMAIN : 'bluemsp',
            FROM_USER_ID : '1001',
            DATE_CREATED : '2017-12-06-18-08-01',
            DURATION : '360',
            TRANSCRIPT : 'testing transcripts generated by GSR API',
            TO_USERS : [
                        {TO_USER_ID : '1001'},
                        {TO_USER_ID ; '1019'}
                        ]
        }
}'''

print("request : ", data)
response = requests.post(url, data=data)
print("response : ", str(response))